<h1>Scientific coding bootcamp notebook 1: Intro to Julia.</h1>
Welcome to Julia!  This notebook will give you a very rapid overview of the main features of the language.  It presumes you are already familiar with basic programming concepts in some other language. 

A very useful feature to know about up front is the "help mode", which you access by typing ? at the beginning of a cell, followed by anything you want to know more about.  

In [52]:
# This is a comment.  Any line that starts with # is a comment. 
# Defining variables:
x = 2
y = pi
x + y

5.141592653589793

In [54]:
?pi

search: pi Pipe pipeline PipeBuffer tanpi sinpi cospi cispi getpid rem2pi mod2pi



```
π
pi
```

The constant pi.

Unicode `π` can be typed by writing `\pi` then pressing tab in the Julia REPL, and in many editors.

See also: [`sinpi`](@ref), [`sincospi`](@ref), [`deg2rad`](@ref).

# Examples

```jldoctest
julia> pi
π = 3.1415926535897...

julia> 1/2pi
0.15915494309189535
```


&nbsp;

&nbsp;

The last output of a cell is printed.  You can suppress this by putting a semicolon after the last line.  You can print an intermediate result using the function "println". 

In [4]:
println(y*2)
#= This is a multi line comment. starts a multi line comment. 
The variable c below is a single character, made via single quotes. 
The variable s below is a string, made with double quotes.
Multiline comments end with =#
c = '!'
s = "Hello friend!"; 

6.283185307179586


You can get unicode symbols by typing \ followed by the symbol name and hitting the tab key.  Try this below. Make the π symbol.  Print it and see what value it gives. 

In [ ]:
# Your code here.

Here are some other useful data types. 

In [22]:
# Boolean
b = true

# Dictionary
d = Dict("hello"=>"foo",2=>"baz")

# Vector
v = [1 , 2 , 3.7 , -12.6]

# Matrix
M = [1 2 3 4 ; -1 -2 -pi -12 ; 0 0 0 0 ; 1 NaN -Inf Inf]

4×4 Matrix{Float64}:
  1.0    2.0    3.0        4.0
 -1.0   -2.0   -3.14159  -12.0
  0.0    0.0    0.0        0.0
  1.0  NaN    -Inf        Inf

In [24]:
# Access elements of vectors, matrices, and dictionaries with square brackets [...], like this:
println(M[1,2])
println(v[3])
println(d["hello"])
M[1,2:4]   # This is called slicing.  It gives a range of values of the matrix.

2.0
3.7
foo


3-element Vector{Float64}:
 2.0
 3.0
 4.0

Your turn: Try multiplying the matrix M with vector v using the * operator.  
Then multiply the two with the .* operator.  
Can you tell what is the difference between these two operators? 

In [ ]:
# Your work here.

Now onto control flow.  Here are examples of if statements, for loops, and while loops.

In [16]:
if 1 == 1
    println("Alpha")
else
    println("Bravo")
end

if M[1,1] != 2.0
    println("Charlie")
else
    println("Delta")
end

for i=1:4
    println("i==",i)
end

idx = 1
while s[idx] != c   # Look above to see what we defined c and s as.  
    println(s[idx])
    idx += 1        # This increments idx by 1. 
end
println("idx == ",idx," and s[idx] == ",s[idx])

Alpha
Charlie
i==1
i==2
i==3
i==4
H
e
l
l
o
 
f
r
i
e
n
d
idx == 13 and s[idx] == !


A very useful way to construct objects like vectors is with "comprehension":

In [27]:
[i^2 for i=1:4]

4-element Vector{Int64}:
  1
  4
  9
 16

In [26]:
[i^2-j^2 for i=1:4,j=1:4]

4×4 Matrix{Int64}:
  0  -3  -8  -15
  3   0  -5  -12
  8   5   0   -7
 15  12   7    0

Here are two examples of functions.  The first is the "usual way" to define a function, and the second is the short way (typically only used for very simple functions).

In [31]:
function customTranspose(M::Matrix)
    # This function transposes a matrix.  
    m,n = size(M)   # Get the size of M in both dimensions
    M_transposed = zeros(Float64,n,m)   # Make an array of zeros
    for i=1:m
        for j=1:n
            M_transposed[j,i] = M[i,j]
        end
    end
    return M_transposed
end

elementwiseSquare(M::Matrix) = [M[i,j]^2 for i=1:size(M,1),j=1:size(M,2)]

elementwiseSquare (generic function with 1 method)

In [32]:
customTranspose(elementwiseSquare(M))

4×4 Matrix{Float64}:
  1.0    1.0     0.0    1.0
  4.0    4.0     0.0  NaN
  9.0    9.8696  0.0   Inf
 16.0  144.0     0.0   Inf

The last basic concept to understand is types and methods. 1 is an Int64 type, whereas 1.0 is a Float64 type.  You can see the type of an object via the function typeof:

In [34]:
println(typeof(1))
println(typeof(1.0))
println(typeof(s))
println(typeof(M))

Int64
Float64
String
Matrix{Float64}


The type of M is more complicated, because it contains other variables within it, which themselves have a type. 

You can define your own custom types using the keyword struct.  A custom struct contains "fields" which you access via the dot syntax "structname"."fieldname".

In [40]:
struct MyType
    x::Int
    y::Float64
    name::String
end

x = MyType(12,pi,"Wabbit")
x.name

"Wabbit"

One of the most powerful features of Julia is the ability to make functions behave differently for different combinations of input types.  This is called "multiple dispatch".  Each different definition of a function for different combinations of arguments is called a "method" for that function. 

In [39]:
function test(x::Int)
    return floor(x/2)
end
function test(x::Float64)
    return x/2
end
println(test(3))
println(test(3.0))
test

1.0
1.5


test (generic function with 2 methods)

Your turn!  You're going to make a custom type representing a quaternion, and then you're going to define addition and multiplication for this type. 

A quaternion is a like a 4-dimensional complex number.  Instead of just one imaginary unit i, it has three imaginary units i,j,k, which satisfy i^2 == j^2 == k^2 == -1.  They also have multiplication rules among themselves: 
ij = k
jk = i 
ki = j
ji = -k
kj = -i
ik = -j

Make a quaternion struct with fields r, i, j, and k for the real part and each complex part, respectively.  Then define a new methods for the + and * functions which handle two quaternions.  You get starter code below.

In [ ]:
struct ...

end

function +(x::Quaternion,y::Quaternion)

end

function *(x::Quaternion,y::Quaternion)

end

A couple miscellaneous useful things:

In [43]:
# A way to make an "anonymous function", i.e. one without a name:
(x -> x^2)
# You can assign an anonymous function to a variable:
f = (x -> x^2)
# Apply an anonymous function just as a regular function:
println(f(10))
(x -> x^2)(12)

100


144

In [45]:
# Functions can be applied using the operator |>
# Whether you use this or regular function composition is purely a matter of taste.
println(10 |> f)
4 |> f |> f

100


256

In [56]:
# Any function can be applied elementwise to an array by putting a dot after the function. 
f.(M)

4×4 Matrix{Float64}:
 1.0    4.0   9.0      16.0
 1.0    4.0   9.8696  144.0
 0.0    0.0   0.0       0.0
 1.0  NaN    Inf       Inf

In [48]:
# Packages are imported with the using keyword.
# If you get "ArgumentError: Package Date not found in current path." then
# type "]add Date" to automatically download the package. 
using Dates
now()

2024-07-26T16:34:38.336

In [49]:
]add Dates

   Resolving package versions...
    Updating `C:\Users\anonc\.julia\environments\v1.10\Project.toml`
  [ade2ca70] + Dates
  No Changes to `C:\Users\anonc\.julia\environments\v1.10\Manifest.toml`


Play around with the output of now().  See what it's type is, and see what its field names are using the "fieldnames" function.  Use help mode to figure out how this function works.

In [62]:
# A very useful special operator is the three dots "...", which is called the splat in Julia.  
# It allows you to unpack the contents of a list or vector into function arguments.  Here are some examples: 
function splatTest1(a,b,c)
    return a+b*c
end
splatTest1([2,3,4]...)

14

In [63]:
# The splat also is used in defining "varargs functions", i.e. functions which can take different numbers of arguments.
function splatTest2(a,b...)
    println("You input a=",a)
    println("You input b=",b)
    return b[1]
end
splatTest2("Hello", " there", " friend.")

You input a=Hello
You input b=(" there", " friend.")


" there"

In [67]:
# You can provide keyword arguments to functions like this.  Note that you cannot do multiple dispatch on keyword arguments. 
function keywordTest(s::String; num::Int=1)
    println( *([s for i=1:num]...))                 # Think about this line.  What is going on here?
end
keywordTest("Hello "; num=10)

Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello 
